<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms><RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained><PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile><DebugType>None</DebugType><DebugSymbols>false</DebugSymbols>
    <ApplicationIcon>appMain.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="System.Speech" Version="10.0.0" /></ItemGroup>
  <ItemGroup><None Update="config.ini"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None></ItemGroup>
  <ItemGroup><Content Include="appMain.ico"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup>
</Project>
